# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4092bc710a52b0dc9b3acf653056affc1639af6be90df243e42fe47933242b6f03339703f699a47f31a51b4f892851296d0bc4a8bc2cf83a04f481fb73185407

test:
  secret_key_base: b0f390ce42adcf5701ecc91a6e44b4ae49f1b28207c39c033639d9486e7497670bba0624a63a1bed514fa7c2540355b7da46ba2bb78a6793bac24ef488d0e2e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
